### ISSUE TITLE
Error: MySQL server has gone away, needs to reconnect/re-open the connection

### ISSUE THREAD

**Issue by extremeshok** [ovpn-to/oVPN.to-nntp2nntp#9]
````
1530093986.31:  def mysql_query_update_bestats: failed, exception = '(2006, 'MySQL server has gone away')'1530093986.31:  def mysql_query_update_bestats: failed, exception = '(2006, 'MySQL server has gone away')'1530093986.31:  def mysql_query_update_bestats: failed, exception = '(2006, 'MySQL server has gone away')'


1530093986.32:  def mysql_query_update_bestats: failed, exception = '(2006, 'MySQL server has gone away')'
1530093986.32:  def SQLCONNFAIL(): failure = '[Failure instance: Traceback: <class '_mysql_exceptions.OperationalError'>: (2006, 'MySQL server has gone away')
/usr/lib/python2.7/threading.py:801:__bootstrap_inner
/usr/lib/python2.7/threading.py:754:run
/usr/lib/python2.7/site-packages/twisted/_threads/_threadworker.py:46:work
/usr/lib/python2.7/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/usr/lib/python2.7/site-packages/twisted/python/threadpool.py:250:inContext
/usr/lib/python2.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/lib/python2.7/site-packages/twisted/python/context.py:122:callWithContext
/usr/lib/python2.7/site-packages/twisted/python/context.py:85:callWithContext
/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py:477:_runInteraction
/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py:469:_runInteraction
Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 474, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 70, in rollback
    raise ConnectionLost()
twisted.enterprise.adbapi.ConnectionLost: 

Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 474, in _runInteraction
    conn.rollback()
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 56, in rollback
    self._connection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

Rollback failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 474, in _runInteraction
    conn.rollback()
  File "/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 70, in rollback
    raise ConnectionLost()
twisted.enterprise.adbapi.ConnectionLost: 
````

**Comment by scriptzteam** [comment]
"MySQL server has gone away", so mysql gone away is not a script itself error, its mysql error i think ;) get a better server that performs better with mysql :D

**Comment by ovpn-to** [comment]
try different mysql plugin
